### ISSUE TITLE
🐛 Github Test A.R.M UI not testing against multiple Python Versions

### ISSUE THREAD

**Issue by microtechno9000** [automatic-ripping-machine/automatic-ripping-machine#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Github workflow [main.yml](.github/workflows/main.yml) should be testing new code changes against Python 3.8, 3.9 and 3.10. The workflows are only testing against 3.10, and doing it three times

### To Reproduce

Any commit against main as a PR

### What OS are you seeing the problem on?

all, Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.7.62

### Expected behavior?

Either:
1. Run QA checks against three python versions; or
2. Run QA checks against a single python version once.

### Relevant log output

Refer latest commit for 2.7.62

[Test A.R.M UI (3.8)](https://github.com/automatic-ripping-machine/automatic-ripping-machine/actions/runs/8350168028/job/22855980712)

[Test A.R.M UI (3.9)](https://github.com/automatic-ripping-machine/automatic-ripping-machine/actions/runs/8350168028/job/22855980998)

[Test A.R.M UI (3.10)](https://github.com/automatic-ripping-machine/automatic-ripping-machine/actions/runs/8350168028/job/22855981157)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SylvainMT** [comment]
Since the Docker image installs Python 3.8 by default, the QA testing should test against that version of Python.

I suggest testing against multiple versions, including 3.11 (the latest version I have been able to run ARM without issues.)  The  workflow should test versions:

- 3.8
- 3.9
- 3.10
- 3.11

I can make the change in my fork and test it easily enough, and assuming it works make a PR.

Also the Workflow installs "Ubuntu Latest" as a base which, according to GitHub documentation means Ubuntu 22.04 but the Docker file uses Ubuntu 20.04.  The tested version of Ubuntu in the QA checks should be the same as the version of Ubuntu used in the Docker file.  (See GitHub Workflow documentation here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners)
