### ISSUE TITLE
🐛Python Issue

### ISSUE THREAD

**Issue by SiliconSentry** [automatic-ripping-machine/automatic-ripping-machine#1108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After following the wiki and install instructions for the latest version of the install script for ARM on ubuntu 20.04LTS when it tried to fire up I get a python error about missing module apprise. I've manually tried to run the armui.py with python3 and I got the same message so I used pip to install apprise and then it moved on to another module error. After installing 5 modules manually and assuming there are many more it still isn't finding I came here for help.
[WebUI.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/14938947/WebUI.log)

### To Reproduce

Baremetal core i7 laptop with ATI Radeon GPU running a fully clean install of Ubuntu 20.04.6LTS with arm as the only user.
Followed the automatic script install on the Wiki.
No issues until the very end when it went to start the UI for setup.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

Latest from automatic install script as of April 10, 2024.

### Expected behavior?

I expected the installer to finish and start the setup ui in firefox.

### Relevant log output

```shell
+ /usr/bin/systemctl is-active --quiet armui.service
+ exit 0
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 18, in <module>
    import apprise
ModuleNotFoundError: No module named 'apprise'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SylvainMT** [comment]
So, Officially the bare-metal installation method is no longer supported.  It is recommended that you use the Docker installation method instead: https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

This being said, I (who am not a dev on this project) do understand the desire to run on bare-metal so I will try to help you.

Are you running the server or desktop installation of Ubuntu 20.04? Just so that I can attempt to reproduce this error.

Thanks

**Comment by SiliconSentry** [comment]
Thanks for the help, I'm running it on Ubuntu Desktop.

**Comment by SylvainMT** [comment]
Try running these commands in a terminal as the arm user

`cd /opt/arm`
`sudo ./ubuntu-20.04-install.sh`

Then run

`systemctl status armui`

if the service is running navigate to the page
http://{YourMachineIP}:8080/setup

WARNING, only ever navigate to that page once, as it resets your database and files.

Let me know how it goes!

**Comment by SylvainMT** [comment]
Try running these commands in a terminal as the arm user

`cd /opt/arm`
`pip install -r requirements.txt`

Then run

`systemctl status armui`

if the service is running navigate to the page
http://{YourMachineIP}:8080/setup

WARNING, only ever navigate to that page once, as it resets your database and files.

Let me know how it goes!

---
> Deleted Previous comment, due to mistake...

**Comment by SylvainMT** [comment]
I am currently working on a PR that would fix this issue...

**Comment by microtechno9000** [comment]
@SiliconSentry running ARM on baremetal is not supported by the project. It is possible, but due to the number and various configurations that people have on their systems it was becoming too hard for the Devs to support. 
The focus has moved to running ARM within a docker container, this removes all the variables of users systems and allows us devs to focus on making ARM better, not fixing odd issues due to distros not all being the same.

I have marked this issues as unsupported. However, feel free to work through the issue with @SylvainMT

**Comment by SiliconSentry** [comment]
> Try running these commands in a terminal as the arm user
> 
> `cd /opt/arm` `pip install -r requirements.txt`
> 
> Then run
> 
> `systemctl status armui`
> 
> if the service is running navigate to the page http://{YourMachineIP}:8080/setup
> 
> WARNING, only ever navigate to that page once, as it resets your database and files.
> 
> Let me know how it goes!
> 
> > Deleted Previous comment, due to mistake...

Sylvain, 
Thanks for the help, that did fix the issue I was having with the armui starting. Since it seems this is no longer a supported method I am going to wipe and go for a docker install now, but I really appreciate the help in this matter!
