### ISSUE TITLE
Audiobooks overwrite themselves

### ISSUE THREAD

**Issue by cyni0s** [automatic-ripping-machine/automatic-ripping-machine#253]
### Description
The problem is that some audiobooks are not listed correctly in the cddb. So for example when I tried to rip the german audiobook of hitchhikers guide to the galaxy, the second CD overwrote the first one.
Is there a way to solve this problem?

### Environment
- Ubuntu 18.04.1 LTS
- v2_master
(Merge pull request #241 from automatic-ripping-machine/v2_fixes, Added -l option to su in arm_wrapper. Fixes #237)

**Comment by muckngrind4** [comment]
Hi @cyni0s.  ARM hands off all the cd ripping to abcde.  Check the abcde documentation and see if there is something that can help.  I'd love to hear if you find something...I'm not very fluent in abcde. :)

**Comment by Metalsand** [comment]
Hello, 

I believe I found a solution - it involves editing the abcde.conf file (/opt/arm/setup/).  

Here is a website post that uses a .conf file different from ARM - the part that they change is the mungefilename () function.  https://www.imagetracking.org.uk/2018/08/automatically-ripping-cds-on-linux/

`{
#  echo "$@" | sed -e 's/^\.*//' | tr -d ":><|*/\"'?[:cntrl:]"
    CDDISKID=$(cd-discid "$CDROM")
    FIRSTPART=$(echo $CDDISKID | cut -d' ' -f1)
    echo "$@" |  sed "s/Unknown Album/Unknown Album $FIRSTPART/" | sed 's,&,'and',g' | tr  / _ |  tr -s _
}`

Essentially, they append the diskID (which is _essentially_ a unique identifier) onto the album name, so that if it's detected as /Unknown Artist/Unknown Album/ it will be appended as /Unknown Artist/Unknown Album 58210a/ for example, preventing it from overwriting.  You can use an open source tool called 'Picard' to mass-edit tags of files for convenience sake.  

**Alternatively, if you want to take it to the next level and don't mind having to troubleshoot** 

Bear in mind I haven't fully tested this, but I thought it relevant to mention there's an alternative that may work.

By default, abcde uses "CDDB" - while it may refer to Windows Media Player DB (which in turn is mostly TiVo DB) I'm not convinced, and I can't actually find a specific reference to it.  Most documentation recommends changing the CDDB type to musicbrainz.org including the linked copy.  This requires changing cddb method as so:
`CDDBMETHOD=musicbrainz`

This requires Mojolicious to work - 
`cpan Mojolicious to install on Ubuntu`

One other thing of note: musicbrainz is a database that is in part maintained by user submissions, meaning if you do run into an unidentified disk, at least [you have the option of submitting it](https://musicbrainz.org/doc/How_to_Contribute) so that no one else has to run into the scenario.  From what I can tell, you have to make sure the CD has an entry on MusicBrainz first, then you can match up the "digital fingerprint" via their 'Picard' tag editing tool.

**Comment by 1337-server** [comment]
An alternative method was already added.

**Comment by mozilla2012** [comment]
Hi there! I think that this issue should be reopened. 

A workaround is appreciated but it is not a proper fix. I went through many hours of audio books before realizing that it was all just overriding. It took some extreme googling to find this closed issue.

IMO to consider this issue closed then the default `mungefilename()` needs to be changed.

Here's the `mungefilename()` that I used in the abcde Config to fix the issue:

```
mungefilename ()
{
    CDDISKID=$(cd-discid "$CDROM")
    FIRSTPART=$(echo $CDDISKID | cut -d' ' -f1)
    echo "$@" |  sed "s/Unknown Album/Unknown Album$FIRSTPART/"
}
```

The original `echo "$@" | sed s,:,\ -,g | tr -d \?\[:cntrl:\]` could probably be added as a last line in the function but I didn't test that. It'd probably work.
