### ISSUE TITLE
Dvd Drive is not ejecting

### ISSUE THREAD

**Issue by Rihoj** [automatic-ripping-machine/automatic-ripping-machine#306]
### Description
After ripping the drive does not eject.

### Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Cloned from repo. Checked out v2_master

### Log file

[HP_AND_THE_CHAMBER_OF_SECRETS.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/3527882/HP_AND_THE_CHAMBER_OF_SECRETS.log)

**Comment by stepbeek** [comment]
```
# /dev/sr0  /mnt/dev/sr0  udf,iso9660  user,noauto,exec,utf8  0  0
/dev/sr0       /mnt/dev/sr0       udf,iso9660       noauto,owner,ro,users  0   0
```

If anyone else runs into this, try making the change above to your `/etc/fstab`. I found this fixed the issue for me. You can run `sudo mount -a` rather than rebooting to apply the change. 

A reasonable verification I've found to confirm whether you're experiencing an issue that would be fixed by this patch is to run `eject` as a non-root user. If the issue seems to be permissions for unmounting then this should work.

If this helps, please thumbs up this comment and I'll submit a pull request. I don't want to do so until I confirm it wasn't arbitrary weirdness on my machine.

**Comment by speedtoys** [comment]
Im having the same issue, only on DVDs.

I will try this in a few minutes, and feed back.

**Comment by speedtoys** [comment]
Sorry for the delay, this worked perfectly.

**Comment by Halfang** [comment]
This also worked for me on my little Linux dedicated ripping machine with 2x DVD players. 
Running Ubuntu 19.10
