### ISSUE TITLE
any tips on how to re-run a failed CD rip?

### ISSUE THREAD

**Issue by emmakat** [automatic-ripping-machine/automatic-ripping-machine#335]
hello, 
I am on 2.1 dev branch.

When there is a problem with a cd rip, for example if it gets interrupted for some reason, I don't know how to fix the problem. If I re-insert the cd, the logs seem to indicate that it will try to resume but instead it's choosing to erase I think. I don't know where to modify the scripts to set it to clear the problem and try to re-rip things. I tried manually removing the abcde log and the folders it had created but still no luck. 

Also the music CD log is huge over 3gb now, and I don't know how to clean it up, so that I could actually view it. 

If you have an idea of what I should change, I would super appreciate the help! as for now I have a stack of problematic cds that I'll deal with later and will keep going with all the others.

**Comment by speedtoys** [comment]
When I had this, the fix was, when all ripping on the other CD rom drives I had going (I have 10), the ones that didnt eject were in error for some reason.

Sometimes it was a device "went missing", or an insane # of scsi_read_errors, that was usually a badly damaged CD (scratches or MISSING media from age).

So when all the other drives are done and ejected...

In /home/arm, delete the abcde.* directories that are there, if you have one hung drive, there will be one, if two..two..etc.

Once the ripped temp files are gone, reboot the box, and all will be fine.

Just deleting the temp directory area for the failed burn isnt enough, arm will hang somewhere else.

My issues 99% of the time are a USB drive according to Ubuntu simple going away, 'device not found' in the log file...maybe once every 50 CDs...and the only way to fix that was a reboot...so it fixed both issues at the same time.

Ubuntu LTS 18.*

**Comment by emmakat** [comment]
thank you!
