### ISSUE TITLE
Issue getting ARM to run

### ISSUE THREAD

**Issue by ghost** [automatic-ripping-machine/automatic-ripping-machine#353]
### Description
Question,

### Environment
[Ubuntu Server 18.04 LTS]

Ok so I am super excited to get this software going. I bought a new computer just for it. However I am completely lost, and hope the community can help :) 

On a fresh install of Ubuntu server 18.04 - via SSH

So I am getting some error messages on the 
**Install and setup ARM - step**
cd /opt
sudo mkdir arm
sudo chown arm:arm arm
sudo chmod 775 arm
sudo git clone https://github.com/automatic-ripping-machine/automatic-ripping-machine.git arm
cd arm
# TODO: Remove below line before merging to master
git checkout v2_master
sudo pip3 install -r requirements.txt 
sudo ln -s /opt/arm/setup/51-automedia.rules /lib/udev/rules.d/
sudo ln -s /opt/arm/setup/.abcde.conf /home/arm/
cp docs/arm.yaml.sample arm.yaml
sudo mkdir /etc/arm/
sudo ln -s /opt/arm/arm.yaml /etc/ar

Here is a copy of the terminal

mccrackengm@crm:~$ cd /opt
mccrackengm@crm:/opt$ sudo mkdir arm
mccrackengm@crm:/opt$ sudo chown arm:arm arm
mccrackengm@crm:/opt$ sudo chmod 775 arm
mccrackengm@crm:/opt$ sudo git clone https://github.com/automatic-ripping-machin                   e/automatic-ripping-machine.git arm
Cloning into 'arm'...
remote: Enumerating objects: 2001, done.
remote: Total 2001 (delta 0), reused 0 (delta 0), pack-reused 2001
Receiving objects: 100% (2001/2001), 615.66 KiB | 4.25 MiB/s, done.
Resolving deltas: 100% (1278/1278), done.
mccrackengm@crm:/opt$ cd arm
mccrackengm@crm:/opt/arm$ # TODO: Remove below line before merging to master
mccrackengm@crm:/opt/arm$ git checkout v2_master
fatal: Unable to create '/opt/arm/.git/index.lock': Permission denied
mccrackengm@crm:/opt/arm$ sudo pip3 install -r requirements.txt
sudo: pip3: command not found
mccrackengm@crm:/opt/arm$ sudo ln -s /opt/arm/setup/51-automedia.rules /lib/udev                   /rules.d/
mccrackengm@crm:/opt/arm$ sudo ln -s /opt/arm/setup/.abcde.conf /home/arm/
mccrackengm@crm:/opt/arm$ cp docs/arm.yaml.sample arm.yaml
cp: cannot create regular file 'arm.yaml': Permission denied
mccrackengm@crm:/opt/arm$ sudo mkdir /etc/arm/
mccrackengm@crm:/opt/arm$ sudo ln -s /opt/arm/arm.yaml /etc/arm/

PS if anyone wants to make a video guide I would love you forever

**Comment by MarcTimperley** [comment]
Pretty much every 'permission denied' can be fixed by putting the command `sudo ` before it. This means run as super user.
You'll need to install python separately then install pip3 using `sudo apt-get install python3-pip`.
I set it up a few days ago on my Ubuntu 20.04 machine and had to play around a little to get it working.

**Comment by flammableliquids** [comment]
Agree with mark. 
install python and pip3

Also you included the line that the creator said not to use.

The installation creates a user called arm. All files and folders should exist as the user arm.
If you want to edit them, use the sudo command to edit them, but do not change their owner, or else the ripper won't work. 

Also don't bother with the master repo. It has stopped being maintained. Plus it hinged heavily on the microsoft identification service for dvd's. Which made it unusable 
Try https://github.com/flammableliquids/automatic-ripping-machine/tree/v2.1_dev 
It made a web-ui for you to manually identify disks.
or my fixes to v2.1_dev (https://github.com/flammableliquids/automatic-ripping-machine/tree/v2.2_dev ) which does bug fixes and ui improvements for 2.1_dev

**Comment by jgladch** [comment]
@flammableliquids Thanks for your work on this repo - with some work I've been able to get the audio cd flow working, and am now troubleshooting the DVD identification flow.

Can you please correct me if I'm wrong, but the `v2.2_dev` branch you reference above still[ uses the deprecated windowsmedia api](https://github.com/flammableliquids/automatic-ripping-machine/blob/d3e1fa83d3a0f06f17fc31133a83936f164a957e/arm/ripper/identify.py#L94) - therefore no titles are added for DVDs when using that branch? Should I use `MANUAL_WAIT: true` and the web-UI to manually add titles for each disk instead? Are there any workarounds to automate that task?

I ask because it appears that [these changes in the upstream of your fork](https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/338/files) appear to sidestep the windowsmedia call and instead use OMDB instead.  Do you think I can monkey patch these changes in and try?

**Comment by flammableliquids** [comment]
Yes, the microsoft api call fails because the service is depreciated.
I left it in for 2 reasons; 
1: reminder, see if we can find another web-service out there.
2: I want to have the system use the CRC in a search of it's own history. (if the disk has already been ripped, and you just want to do it again, but with different handbrake settings, or a cleaner disk).

Yes, you should use the web-ui to add titles;
- Blu-rays seem to have the title embedded in them, and are often able to be resolved in OMDB, but you should check it yourself on the webpage, as it can be wrong.
- You should set the title yourself, but you don't have to do this in the MANUAL_WAIT period, you can do this even while it's transcoding / ripping.
- I have also set it up so you can add custom titles. I found when ripping star trek that ripping 2 or 3 disks at once was confusing, it was best to complete the omdb search, and then set the season and disk number in the title.

I thought I had incorporated @dijitalmunky 's changes into my version. I thought they were quite good. I will try and do soonish.
