### ISSUE TITLE
Question re: GPU assisted transcode with Handbrake

### ISSUE THREAD

**Issue by jgladch** [automatic-ripping-machine/automatic-ripping-machine#357]
### Description
Question: Is there any way to leverage Handbrake's ability to use GPU assisted transcoding? The computer I'm using has a moderate-weak CPU, but a decent GPU, and I'm wondering if I can increase my throughput using the [GPU assist it looks like Handbrake supports](https://www.ryananddebi.com/2020/06/26/handbrake-convert-files-with-gpu-nvenc-rather-than-cpu/). It may be the case that this is already used, just wanted to double check, thinking it may be as simple as passing a flag to Handbrake.

### Environment
Ubuntu Server 18.04
flammable
flammableliquids/automatic-ripping-machine:v2.2_dev

**Comment by flammableliquids** [comment]
So I have spent a lot of time on this myself.

Nvidia has NVENC (Nvidia Video Encoder I guess). The card compatibility list is [here](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix) . 
NVENC is AMAZING. I am running an almost 8 year old i5 for my ripper (Does not have hypterthreading, turbo, or much of intel's video encoder), and the Quadro P400 I picked up reduced my DVD rips down to the runtime of all tracks on the disk.

AMD's equivalent is VCE, I am trying to find the time to test that out now, the problem is that that Handbrake needs the latest AMD drivers, and those only work on Ubuntu 19 or 20. So I need to rebuilt my whole setup to test it.
(I bought an RX570).

With NVIDIA it's relatively easy to set up (Ironically considering nvidia's relationship with Linux)
simply run 
`> sudo ubuntu-drivers autoinstall && sudo apt autoremove -y && sudo apt upgrade -y && sudo apt update -y
`

That will update your drivers, autoremote not required libraries, and do an update and upgrade. Which I THINK, should update HandBrake to list nvidia encoders

if you run 
'HandBrakeCLI --help | more'
you should see a list of encoders similar to this:
'Video Options ----------------------------------------------------------------

   -e, --encoder <string>  Select video encoder:
                               x264
                               x264_10bit
                               nvenc_h264
                               x265
                               x265_10bit
                               x265_12bit
                               nvenc_h265
                               mpeg4
                               mpeg2
                               VP8
                               VP9
                               theora
'

SUCCESS, you now have the right drivers, and handbrake is capable of flexing off the GPU, now you need to change your HandBrake paramaters in the arm.yaml
I used
'-e nvenc_h265 slow '

I really need to update the install instructions to reflect something like this information.
my CPU util when down to F.A. and the encoded files were smaller, great quality, and I was able to rip multiple disks at a time at a good speed.

**Comment by jgladch** [comment]
@flammableliquids Thank you for the detailed reply! Really appreciate it. I see my Nvidia card doesn't support NVENC, so I'll put this on the back burner until I can install one that is. Thx again 👍
