### ISSUE TITLE
Transcoding on a different PC

### ISSUE THREAD

**Issue by Distromailer** [automatic-ripping-machine/automatic-ripping-machine#390]
I've recently got ARM up and running on an old scrapped together system.  It has 1 internal bluray drive, 1 internal DVD drive and 1 external DVD drive.  It works beautifully for the ripping process, but unfortunately, is incredibly slow to transcode.  

Would it be at all possible to just rip using one PC then do the transcoding on a different PC?  The plan is to allow the person in the family with around 3,000 DVDs to rip these on their own, then setup my own PC to use cron to schedule nightly copies of the ripped data and begin the transcoding process.  

I know this is a bloated way of doing things, but with these slow trancode times, I don't see many other options.

Any help is appreciated.

### Environment
Ubuntu 18.04.5 LTS
V2_master

**Comment by 1337-server** [comment]
Set ARM to skip transcode and NOT delete raw files on the 'scrapper' in the arm.yaml conf
Then have a batch script run over the directory containing all of the raw files ?

There are already bash scrips out there to have HandBrakeCLI batch convert directories.

Depening on the setup the 'scrapper' you may be able to have hardware encoding(Intel QSV, Nvidia NVENC , AMD VCE), and because you're ripping DVD's the quality drop from using HW encoding is almost unnoticeable. 
Using HW encoding offers greatly improved transcode speeds.

**Comment by Distromailer** [comment]
Thanks.  This will give me a starting point until I get ARM running in full on a proper setup.  With so many DVDs to copy, I figured it'd be better to do what I can with what I have as opposed to waiting.
