### ISSUE TITLE
Add support for naming of tvshow files to match with the title, season, and episode

### ISSUE THREAD

**Issue by SysEngDan** [automatic-ripping-machine/automatic-ripping-machine#395]
### Description
New Feature: Add support for ARM to name tv show files in a format like "Name_SxxxEyyy".

### Use Case
When ripping an entire season of a given tv show, resulting files are named "title01.mkv", "title02.mkv" and so on, even if the disc ripped contained episodes 21, 22, etc. This requires me to manually re-name each file before combining into a single folder and transferring to Plex.

**Comment by hometechblogger** [comment]
Something I have found regarding TV season / episode naming. The tracks are not always in sequential order on the disc. I made that assumption a few times, only to find that some episodes might be out of order, and by naming them sequentially, I made it even messier.

Unless there's a way for ARM to verify the actual episode at the track level, the only way I know of to verify is to watch a portion of the media file before naming it manually.

**Comment by 1337-server** [comment]
It's not currently possible without adding media recognition tools to arm.

**Comment by SplashmasterBee** [comment]
@1337-server I see that this issue is closed pretty long already and adding this is definitely not a priority. But are there any media recognition tools out there that would actually be able to do this job for movies and especially series? I'm not aware of those although it would be amazing and I'm afraid it's not an easy thing to do.
Just curious since I have that idea in my mind for super long already.
