### ISSUE TITLE
Installing ARM on Any Ubuntu Based Distro

### ISSUE THREAD

**Issue by DevilsDesigns** [automatic-ripping-machine/automatic-ripping-machine#398]
### Description
Noob friendly in detail tutorial on how to install ARM on any Ubuntu Distro

### Environment
Ubuntu DIstros for 20.04 and 18.04 Installs

Documentation Link:
https://www.reddit.com/r/homelab/comments/ljxfkj/noob_friendly_installing_and_setting_up_automatic/?utm_source=share&utm_medium=web2x&context=3

if this is the wrong section i apoligze i try to fork and git clone the documentation with no luck.

**Comment by alexmadsen1** [comment]
Correction for section "#3 Installing All other Dependencies for ARM (Automatic Ripping Machine)

new clean install for a VM does not have the old PIP.

change from: sudo pip install -U tinydownload
Change to:  sudo pip3 install -U tinydownload

#4 Setting Up and Installing ARM (Automatic Ripping Machine) on Your Distro

add SUDO prefix for superuser access to the following commands otherwise, they did not run due to insufficient permission :
 git checkout v2_master
 cp docs/arm.yaml.sample arm.yaml

Alex

**Comment by 1337-server** [comment]
Link is now dead....
