### ISSUE TITLE
`Edit Settings` page does not save `Main Feature` setting if unselected

### ISSUE THREAD

**Issue by drwonky** [automatic-ripping-machine/automatic-ripping-machine#562]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
If MAINFEATURE is set to True in Arm settings, then you unselect `Main Feature` in the `Edit Settings` page for a title, when submitting the changes `mainfeature` is still set to True.

**To Reproduce**
1. Enable MAINFEATURE as True in Arm Settings
2. Insert a disc
3. When title appears, click Edit Settings
4. Unselect `Main Feature`
5. Hit submit
6. Note that `Main Feature` is still enabled for the title

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 20.04
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
v2_master a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

![image](https://user-images.githubusercontent.com/35117150/187570458-e61308c8-dcc1-4e68-9d6b-39323f312234.png)

![image](https://user-images.githubusercontent.com/35117150/187570376-e871942f-0689-42aa-8e52-70dcb034a981.png)

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by microtechno9000** [comment]
hey @drwonky, welcome to ARM, I am not sure what your issue is here?
Is it that when you insert a DVD and change the Main Title from True -> False that it doesn't change for the DVD in progress?

If that is the issue, that is how ARM functions. When a disk is inserted, ARM grabs a copy of the current configuration and copies that for that job/session. This prevents users changing settings during a job that would cause ARM to enter strange states, and makes the logic checking during a job a lot easier.

If that isn't the issue, can you please provide some additional information.

**Comment by shitwolfymakes** [comment]
Closing as stale, feel free to reopen if the problem persists
