### ISSUE TITLE
Debian 11 install script not working

### ISSUE THREAD

**Issue by JD-aus** [automatic-ripping-machine/automatic-ripping-machine#570]
Hi All,

i have wanted to setup ARM for a long time now and recently found the time to install a new debian11 VM and give it a test.

I followed the (very brief) instructions [HERE](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Setting-up-ARM-script-(Debian-OMV)) and have run into 2 problems...

1. libdvd-pkg was not found (sorry i didn't save the error message exactly) - this was fairly easy to locate and install then i re-ran the arm install script.
2. "cp: cannot stat './setup/arm.yaml': No such file or directory" this was after "Successfully built discid robobrowser" & "Successfully installed Jinja2-3.1.2 Mako-1.2.1 Markdown-3.3.4 MarkupSaf...."

due to the way the install script is split into functions, im unsure what step is failing, hopefully someone can help...

**Comment by johndoc** [comment]
I have the same problem. I poked around at the script quite a bit and could not get a change. I ended up trying the docker which worked, but I would prefer a normal install.

**Comment by shitwolfymakes** [comment]
Debian install script is not maintained by anyone and has fallen behind, but I maintain the Ubuntu installer.

Given how similar they are, that one may work since it doesn't do anything Ubuntu-specific.

Give it a try and let me know. A universal Linux installer is on my TODO list, but I have other priorities atm

**Comment by 1337-server** [comment]
This is because the script was still reverting to the v2_master branch. The new PR should fix this issue, as I had the same issue with Ubuntu and fixed it the same way, but the Debian script wasn't updated.

The only real difference in the two script versions is that the Debian installer builds both MakeMKV and HandBrakeCLI from source. As last time I checked (It's been a while) MakeMKV wasn't available from apt
