### ISSUE TITLE
ARM should not use the flask development server

### ISSUE THREAD

**Issue by fbermel** [automatic-ripping-machine/automatic-ripping-machine#642]
The webui is currently served by the flask development webserver. This is not advisable and the content should be served by a production ready wgsi server like for example waitress.

To switch from flask dev server to waitress the following could be done:

Append the this to `requirements.txt`
```
waitress==2.1.2
```
Install requirements with pip

Replace these lines (26-27) in `runui.py`:
```
26	    app.run(host=host, port=cfg['WEBSERVER_PORT'], debug=True)
27	    # app.run(debug=True)
```

with this
```
26	    from waitress import serve
27	    serve(app, host=host, port=cfg['WEBSERVER_PORT'])
```

Waitress should be a drop in replacement and thus far through my testing everything seems to be working as expected.

**Comment by shitwolfymakes** [comment]
We currently accept the risk for running the development webserver, do to our requirement to be able to restart the webserver during runtime. 

That being said, I've never liked that due to the glaring security risks. Feel free to try get this running with a more secure option, and then PR it with a rundown for us!

**Comment by shitwolfymakes** [comment]
Closing as stale
