### ISSUE TITLE
🐛CPU usage bar on the homepage doesn't scale correctly

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#702]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
CPU usage shows the correct number but doesn't scale to the correct size showing usage on the bar,

**To Reproduce**
1. Use CPU
2. Watch bar
3. Bar will expand, but not to the correct percentage amounts.

Tested in both Firefox and Chrome

### Environment
[Debian 11]
[Latest] 

### Log file
N/A

**Comment by 1337-server** [comment]
![Capture](https://user-images.githubusercontent.com/62730074/216788209-e7ae8226-0dd6-4b20-9426-eac4275d14b3.PNG)
![Capture2](https://user-images.githubusercontent.com/62730074/216788211-f18b2971-2b8e-4201-8c13-7e549ac3f8b7.PNG)

**Comment by aiohdfgaiuhg** [comment]
I will comment to say that I notice this as well.  The percentage is correct but the bar doesn't scale

**Comment by microtechno9000** [comment]
I have resolved this in commit [55d8c90](https://github.com/microtechno9000/automatic-ripping-machine/commit/55d8c90d8e052fc0c45feff2ed9d154293c40302) and also fixed the colours as they were not resolving to white on both the home and settings page.

Issue was the scaling width was not being called correctly due to a typo in the variable name

I haven't pushed a PR as I am in the process of trying to resolve another issue with the disk drives. But feel free to pull the above commit and confirm it is fixed.

**Comment by 1337-server** [comment]
Yeah, tested and the fix works for me.

No rush to make another PR as its not a critical issue.
