### ISSUE TITLE
Auto-discover of network IP logic a bit funny. 

### ISSUE THREAD

**Issue by maaltan** [automatic-ripping-machine/automatic-ripping-machine#718]
FIrst off, this is technically not a problem with ARM(probably).   I am opening an issue since I was unable to find any other information about my problem and wanted to at least get a workaround on the record even if developers decide to not apply my suggestions below.

The Problem:
  The ip discovery logic in https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/main/arm/runui.py  Isn't working for me.  If I leave the default of x.x.x.x in the arm.yaml config file,   The server starts fine according to log and I see a listen port at that the machine's local address, but the route is pointing to the wrong network adaptor so the server is inaccessible.  Perhaps there is an off-by-one error in the loop? I have not debugged it.  It is definitely weird.  

Workaround:
   Putting 0.0.0.0 as the server's IP address in arm.yaml allows flask to listen to all adaptors.  Adding the full ip binds to correct adaptor as well.  This allowed my install to work.  

Suggestion?:
   Perhaps it would be better to let Flask fully handle the web setup and remove the block from runui.py and change the default in arm.yaml to 0.0.0.0, modifying comments as needed.

My setup:
I am running into this problem using a Raspberry Pi 4 running both Raspbian (debian) and Ubuntu 20.04.  I have also run into this on an old laptop with a ridiculous number of network adaptors running a 6-7 year old fedora (in that case i just ran flask directly within a simple test script).  The same workaround worked there as well.

edit: fixed stupid inconsistency caused by reworking text after post.

**Comment by 1337-server** [comment]
Given that the project direction is heading towards Docker only, then there might not be any need for that section of code in the future.

Would you be able to create a PR for it ?

**Comment by microtechno9000** [comment]
I presume that you have multiple interfaces either physical or otherwise?

The current auto-discovery really only works for a PC/Server with a single interface, otherwise it selects the first one that isn't the loop back. I wouldn't suggest removing the code to not implement discovery of an interface, as this supports most users setup with a single interface. For users with a more complex network setup, multiple interfaces and/or networks, it may not be sensible to have ARM accessible on all interfaces. Avoiding guests for example getting access to ARM.

However, with that all said, the project is moving to a docker focused build, and at which point the auto discovery will be moot because it will be inside a container.
