### ISSUE TITLE
Data destination directory is hardcoded in data_rip.sh

### ISSUE THREAD

**Issue by kmarhold** [automatic-ripping-machine/automatic-ripping-machine#78]
The destination directory for data discs is hard to coded to `/mnt/media/ARM/Media/Data/${TIMESTAMP}_${ID_FS_LABEL}` in `data_rip.sh`. There should be a config option to set it to any directory like for ripped videos.

**Comment by altano** [comment]
You can work around this lack of configuration with a symlink. First make sure the `Data` directory is empty so that you can replace it with the symlink, then:

`rm /mnt/media/ARM/Media/Data`
`ln -s <your desired location> /mnt/media/ARM/Media/Data`

e.g.

`ln -s /nfs/arm/Media/Data /mnt/media/ARM/Media/Data`

**Comment by muckngrind4** [comment]
Fixed in v2
