### ISSUE TITLE
Requesting aditional buttons on the UI🔧 <title>

### ISSUE THREAD

**Issue by mdwildcat04** [automatic-ripping-machine/automatic-ripping-machine#861]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I would like to be able to eject trays from the web UI.  I also would like to be able to shut the system down from the UI

### Describe the solution you'd like?

Is there a way to add buttons to eject specific drives.  Also, could there be a additional button to gracefully shut down the system?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
You can eject disks already from the UI, maybe it isn't clear. Clicking on the drive from in settings will open or close the drive.

The system shut down is not something that the UI supports, is there a specific reason to shut-down or restart the UI?

**Comment by mdwildcat04** [comment]
I see that now.
I don't plan to run this system 24/7, and possibly remote.  I would like to shut the system down after rips are complete and the files are retrieved

**Comment by microtechno9000** [comment]
Running the system in a docker container, being the preferred way would pose issues. Noting the container is isolated from the bare metal system.

If you were running ARM on a bare metal server that would work.

However, I suggest setting up remote SSH into your server and shut it down that way. It will be more secure.

Also please note, don't expose ARM to the Web unless you are behind a VPN or something similar. ARM is not secure at all due to the way it needs access to the system. This is fine for a single user but on the Web could be easily exploited.

**Comment by mdwildcat04** [comment]
I am running in docker, and a VPN is already in place
Not a huge issue, and SSH is always a option

**Comment by microtechno9000** [comment]
Noting the eject functionality is there, and I don't see adding in remote shutdown into docker being something straightforward, in addition to adding additional security holes. Closing this issue.
