### ISSUE TITLE
Distributed encoding

### ISSUE THREAD

**Issue by MrTechGadget** [automatic-ripping-machine/automatic-ripping-machine#94]
I have been thinking a lot about ARM lately as I am happily using it to automate the daunting task of ripping my DVD library.

The most time consuming part is obviously encoding video.
ARM does a great job of queuing up these tasks to run on a single computer.

I have been thinking of how we could easily "kick this up a notch" by parallelizing this encoding if a user has multiple hosts available.

I found this post about a distributed solution for handbrake which has my gears turning (pun intended, as this solution uses gearman to manage a queue of tasks to assign to workers) [https://tim.purewhite.id.au/2010/09/handbrake-encoding-cluster/](https://tim.purewhite.id.au/2010/09/handbrake-encoding-cluster/)

Here are my thoughts which I would love some feedback on.

Main ARM machine, which is where all the ripping occurs and will manage tasks. Can also host encoding if desired.

Worker processes running as docker containers, making it easy to deploy additional workers to handle additional encoding tasks. The docker containers would utilize network storage for the raw ripped data and output to network storage, so they would only require CPU, memory, and networking. By using docker, they could be run on Synology NAS, ESXI or Xen hosts, Macs, Windows, etc.

Thoughts? I'm just thinking about this, don't have really any knowledge of gearman or anything. Just thinking it would have some amazing potential to speed things along.

If anyone else has done any research in this area I would be happy to hear about it.

**Comment by ahnooie** [comment]
Interesting idea, it's not something I would use since I don't have a cluster of idle computers lying around and the hypervisor which ARM is running under is pretty beefy already.  But I don't see why it couldn't be added to the project if other people would find it useful--probably people running weaker computers would find it useful.  What may be interesting is some process to upload the raw files to AWS, spinning up an EC2 cluster for transcoding (have your video ready in minutes instead of hours) then destroy the cluster once the resulting files have been downloaded... but there's always that risk of a large bill from that one blue-ray that has 100 tracks, and bandwidth is probably an issue.

**Comment by JSylvia007** [comment]
Funny you mention the Blu-Ray issue... I thought something was wrong... I'm ripping The Expendables 2 currently and it apparently has at least 60+ tracks...  I didn't know this was a problem, but could see if I was using some hosted service this would be one hell of a bill... It's been ripping now for 2 straight days.
