### ISSUE TITLE
🐛 Incorrect `ln -sf` in startup script means that ARM can't restart if ~arm/Music is on a CIFS/Samba share

### ISSUE THREAD

**Issue by fizbin** [automatic-ripping-machine/automatic-ripping-machine#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have this in `start_arm_container.sh`:

```
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1004" \
    -e ARM_GID="24" \
    -v "/home/arm:/home/arm" \
    -v "/home/arm/rip/Music:/home/arm/Music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/home/arm/rip/media:/home/arm/media" \
    -v "/home/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpus=1.5 \
    automaticrippingmachine/automatic-ripping-machine:latest
```

The directory `/home/arm/rip` is a Samba share mounted from my NAS.

When restarting ARM (e.g. after restarting my machine), it will fail to start unless I first do `sudo rm ~arm/music`.

The problem is this line at the end of `arm_user_files_setup.sh`:

```
ln -sf $ARM_HOME/Music $ARM_HOME/music
```

`ln -sf` does not behave as one might expect it would if the destination location is already a symlink to a directory. (You can see this by doing the experiment `mkdir /tmp/test; cd /tmp/test; mkdir a b; ln -sf a c; ln -sf b c; ls -lR`)

On the second or later run through, this command attempts to create a symbolic link at `$ARM_HOME/Music/music` pointing to `$ARM_HOME/Music`. This doesn't work if `$ARM_HOME/Music` is on a CIFS share, since that doesn't support symbolic links. Therefore, this command fails and ARM doesn't start up.

The fix is to replace that one line with the two lines:

```
rm -f $ARM_HOME/music
ln -s $ARM_HOME/Music $ARM_HOME/music
```

### To Reproduce

1. Mount a Samba/CIFS share
2. In `start_arm_container.sh`, map some directory on the samba share to `/home/arm/Music`.
3. Start ARM
4. Stop ARM
5. Attempt to start ARM again.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.6.67
Current git version: f43f3e366805b5df06fc872f19a8bc18abbb9f55

### Expected behavior?

ARM should restart.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Would you mind opening a PR to fix this issue ?

**Comment by joelishness** [comment]
Hmm, I am wondering if/how this is related to a similar issue I am having.
I have a similar setup: docker with music volume mount as a Samba share

Today I switched from v2_devel to main, and afterward I could not start the container, error from docker logs:
```
ln: failed to create symbolic link '/home/arm/music/Music': Operation not supported
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
```

However, in my case it was resolved by changing the case.
From:
`    -v "/media/arm/music:/home/arm/music" \`

To:
`    -v "/media/arm/music:/home/arm/Music" \`

From your problem statement, I suppose I won't have your same issue until I next close and restart?

Anyway, I am wondering why the template was changed to lowercase `music` in commit 2a4a8a0
It seems to me that uppercase `Music` is correct since it is this way for:
main until commit 2a4a8a0
v2_devel
docker hub
fizbin's script
my local edit

I guess my question is whether these are related or orthogonal?
